---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: 'test/roles'

verifier:
  name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - role[war_hotel1]
