---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: 'test/roles'
  environments_path: test/environments
  client_rb:
    environment: test_environment

verifier:
  name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - role[war_hotel1]
