FROM <%= @instance['docker_image'] %>

RUN rm -Rf /usr/local/tomcat/webapps/ROOT

<% if @instance['conf'] %>
COPY conf/* /usr/local/tomcat/conf
<% end %>
<% if @instance['libs'] %>
COPY lib/* /usr/local/tomcat/lib
<% end %>
