FROM <%= @instance['docker_image'] %>

RUN rm -Rf /usr/local/tomcat/webapps/ROOT

<% if @change_conf %>
COPY conf/* /usr/local/tomcat/conf/
<% end %>
<% if @change_lib %>
COPY lib/* /usr/local/tomcat/lib/
<% end %>
<% if @change_env %>
COPY bin/setenv.bat /usr/local/tomcat/bin/setenv.bat
<% end %>
